version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DEV=true
    restart: unless-stopped
    ports:
      - "8056:8056"
    volumes:
      - ./backend:/app
      - ./static:/vol/static_dir
      # - static-data:/vol/static_dir
      # - ./log:/var/log
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8056"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DEBUG=0
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - STATIC_DIR=${STATIC_DIR}
      - MEDIA_DIR=${STATIC_DIR}/media
      - LOG_DIR=/var/log
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5439:5432"
    volumes:
      - school-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  school-data:
  static-data:
