# Generated by Django 5.0.2 on 2024-03-01 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_classes',
        ),
        migrations.RemoveField(
            model_name='class',
            name='academic_term',
        ),
        migrations.RemoveField(
            model_name='class',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_classes'),
        ),
    ]
