# Generated by Django 5.0.3 on 2024-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='contact_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
