# Generated by Django 5.0.3 on 2024-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paymentreceipt_arrear_payment_paymentreceipt_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='First Term is 1, Second term is 2, Third term is 3', null=True),
        ),
    ]
