# Generated by Django 5.1.1 on 2024-09-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_academicterm_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeegroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
    ]
