# Generated by Django 5.0.2 on 2024-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expenditure_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='payment_method',
            field=models.CharField(choices=[('Mobile Money', 'Mobile_Money'), ('Bank', 'Bank'), ('Cash', 'Cash')], default='Bank', max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('Mobile Money', 'Mobile_Money'), ('Bank', 'Bank'), ('Cash', 'Cash')], default='Bank', max_length=200),
        ),
    ]
